### ISSUE TITLE
Struggling with font change to fix character limit. 

### ISSUE THREAD

**Issue by Prussia22** [marcussacana/StringReloads#14]
I appreciate these tools being made for VN translation and I'm interested in translating _Anata ni Koi Suru Ren'ai Recette_. I've installed the plugin and got it to work after a lot of confusion but now I'm stuck on a character limit issue. 
![image](https://user-images.githubusercontent.com/69440169/179742875-0c564d14-2730-4afc-86fc-e749e682b1a9.png)
There it cuts off. I see there is a part of this for font stuff, which I assume is to help with issues like this, but I can't get it to work. I've been using the included [Font.0] in SRL.ini and changing its settings as well trying the different hooks but the text doesn't seem to change.

**Comment by marcussacana** [comment]
First, you should try a obvious font change like the System font that make the text look like a old computer.
While that don't works the font hook isn't working at all.
If the font changed, now is the time to try change the size, modify the Width/Height value and check if anything changes.
If nothing changes, no lucky here, since this method isn't compatible with all games that is expected.
You may try find in the game script where he set the font size or modify the engine, and that's a bit hard.

**Comment by Prussia22** [comment]
The text hook doesn't appear to be working as far as I can tell. Within the data.pac file in the game there is a file called "SYSTEM.ini". 
[SYSTEM.txt](https://github.com/marcussacana/StringReloads/files/9142352/SYSTEM.txt)
I tried changing the FONT_SIZE as well as the DEF_FONT_TYPE then repacking as a ".pac" using UnisonShiftManager, but the text and font don't seem to change. The file also mentions DEFAULT_FONT.DAT, which is a file I don't know how to view or edit. Any ideas?

**Comment by marcussacana** [comment]
that DEFAULT_FONT.DAT means that the game is using a pre-renderized font.
it will require special tools to modify the game font.

**Comment by Prussia22** [comment]
Could you point me toward somewhere where I can find these tools?

**Comment by marcussacana** [comment]
this is the problem probabbly there are no tools for this, will need create a new one.
