### ISSUE TITLE
Question regarding string replacing

### ISSUE THREAD

**Issue by Cosmi90** [marcussacana/StringReloads#16]
Hi,

Really nice tool, using it to change fonts was pretty straight forward and results were good.

However I've got another question, I'm currently working on a translation of a game which has menus built in the .exe file.

Now most of the menus I was able to translate through simple hex editing and resource hacker, but some of the strings are either not defined through resources or are not static and as such I was not able to replace them through hex editing.

This is an example:
![Capture](https://user-images.githubusercontent.com/1528939/212371637-2f282207-eae7-4471-a8b2-46587a8d2e2f.PNG)

Can StringReloads be used to somehow translate these?

Thanks

**Comment by marcussacana** [comment]
Legacy SRL maybe can be used for that, https://github.com/marcussacana
/StringReloads/tree/DotNetFramework
But this feature it was removed because I really didn't liked it, there are many windows functions that should be hooked to everything became translatable then the SRL support became just partially, therefore I just removed the feature to translate window forms.
In any way, still possible do that by manually patching the game engine, but it will require a bit of Reverse Engenering skills to do that.

**Comment by Cosmi90** [comment]
Got it,
I was afraid that binary patching was the only way to accomplish this, unfortunately advanced things like reverse engineering and disassembling binaries is a little bit beyond my skill set.

But really thanks for your input :)
