### ISSUE TITLE
kirikiri engine

### ISSUE THREAD

**Issue by imKota** [marcussacana/StringReloads#3]
Hello, @marcussacana 
Can you give an example of use with the "kirikiri" engine?

**Comment by marcussacana** [comment]
It's essentially incompatible because the kirkiri is basically a JIT engine.

**Comment by imKota** [comment]
@marcussacana hmm.. this is bad T_T
Maybe you know how to defeat problems with a monospaced font?
![image](https://user-images.githubusercontent.com/24241471/70276742-fed94400-17c1-11ea-94db-a0be7c1d92de.png)

**Comment by marcussacana** [comment]
Nop, but i'm sure is in a .tjs script, give a look.
The Kirikiri is a engine very, but very dynamic, allways have unexpected things in the game, then even if you know how the engine works the library that the game used (like the KAG3 for example) can change everything and make looks like a different engine.

**Comment by imKota** [comment]
> Nop, but i'm sure is in a .tjs script, give a look.

.tjs files encrypted)

**Comment by marcussacana** [comment]
compiled probabbly, I never saw a .tjs encrypted, you are talking about the TJS2, then this is really more hard to work, What i can say to you is search for more kirikiri games, and look for .tjs script with the same name, you probabbly can modify the things with this, but will make the tjs outdated.
To fix crash caused by the outdated tjs it's complex, isn't a thing who don't know much about programming can do.

**Comment by marcussacana** [comment]
Other way, is use a full non-compiled game as base, and import all audio, images and scripts of your game, this will make patch bigger probabbly but it's almost sure will make easy solve your problem.

**Comment by marcussacana** [comment]
As a reference, the nekopara v1 is a cool base game to use with this 'method'

**Comment by imKota** [comment]
hmmmm
I have one working option, but I cannot import "my_hook.dll" into game.exe
for example https://github.com/Inori/FuckGalEngine/blob/master/Krkr/hash_check.jpg 

Could you tell me how to disable it?

**Comment by marcussacana** [comment]
It's hard if you aren't a programmer too, what you can do repack all .xp3 without encryption and remove the .tmp/krkrsteam plugin of the game, then we will stop to check the dll signature.

**Comment by imKota** [comment]
I am a programmer, but more on the web.
Regarding archives, all .xp3 without encryption.

> remove the .tmp/krkrsteam plugin of the game

And here you can in more detail?

**Comment by marcussacana** [comment]
Basically you need create a 'decrypted version' of the game, extract all files and repack back to normal .xp3 with the tlwiki tools and remove the plugin encryption plugin of the kirikiri, and this plugin usually is a file with .tmp extension or a krkrsteam.dll file, sometimes can have other names too as a disguese, in that case you need to search "SetXP3ExtractionFilter" and the dll that contains this string is what take care of the encyption.
After remove the encryption plugin and decrypt all files, then sometimes the engine don't start because some games modify the source code of the kirkiri to don't bootup without the encryption plugin, and to fix that you just need build by yourself the kirkiri engine or copy the executable from another unprotected game, I like use the old version of the nekopara vol.1 executable, usually works without problem.

**Comment by imKota** [comment]
The files themselves are not encrypted, like game archives. But engine scripts are compiled.
Thanks, I'll try it now.
