### ISSUE TITLE
About hacking the rugp engine using StringReloads

### ISSUE THREAD

**Issue by MishaIac** [marcussacana/StringReloads#9]
Hi marcus. I have a problem with the rugp 6.2 engine of the Schwarzesmarken game by age. Through the debugger, I found this function (seen in the screenshot). Then, through the multiline assembler, I assemble the SRL code in the .patch section. After that, I change those two lines to jmp StrInject, and it seems like everything works fine, SRL is initialized, parses one line (parses correctly), but after that, the game immediately crashes. What could be the problem? Maybe the wrong function? Although, perhaps due to the fact that I do not know assembler at all. 
In fact, I tried to do it with your YouTube video, but because I don’t know Portuguese (and English too), it didn’t work.
![image](https://user-images.githubusercontent.com/47920105/128745878-c80f6e0a-aab3-4ec4-8e3e-4e18bcc3a6b8.png)
In any case, I now need help, since the translation of Schwarzesmarken into Russian was ready back in 2017, but I could not insert the translation into the game. I would be grateful for your help.

**Comment by marcussacana** [comment]
Okay, I can think in some possibiliti to this

**Comment by marcussacana** [comment]
Okay, and I can think of some initial possibilities for the case.

First, check the start and end jmp of your patch, as you put a constant address instead of a label it may happen that the jmp has a constant address which causes an error due to random allocation of the program in memory.
(If your jmp starts with 0xE9 should be fine), you can create labels pressing the key `:` in your keyboard with the target instruction selected in the x64dbg


Second, didn't you corrupt the stack? take a look at what I noticed in your code:
![image](https://user-images.githubusercontent.com/10576957/128752284-5200c1e4-c314-4fb6-9492-324d1d5a083e.png)


Third (Optional), I noticed that you passed the EBX register to the SRL, and the EBX is 'loaded' in the instruction:
`mov ebx, dword [ebp+0xC]`
In some cases the game uses the register once, discards and then reloads from its origin, so it may be better to substitute the origin of the register instead of the register itself.
So you can put `mov dword [ebp+0x4], eax` after calling the SRL to ensure the game will use your translation.


Fourth and last (optional): Instead of using multiple push/pop which can cause you confusion, it is more practical to use `pushad`, `popad` which backup/restore all registers at once.
Just keeping in mind that popad rewrites all registers so if you want to end your function with a modified register you need to change the value of the register on the stack, which is where `pushad` put it.

**Comment by marcussacana** [comment]
Also, you put a `mov [ecx], eax` you really wanted that? by what I can look in code the game are discarding the ecx just after a conditional jmp...
Also, you put the translation (EAX) in the ebx, and [ecx], it's fine if the ECX is really the pointer, but the EBX is replaced by the `pop ebx` in the end of your patch, this mean your patch just restored the original text and returned the game execution without the translation.

**Comment by marcussacana** [comment]
So, I think this should be a working code to your patch
```asm
pushad                    ; backup the registers
call @GetProc             ; get the SRL pointer
push dword [ebp+0x4]      ; get the string pointer and put in the stack
call eax                  ; execute the SRL
add esp, 4                ; Discard the string pointer given to the SRL
popad                     ; restore the  original registers values
mov  ebx, dword [ebp+0x4] ; original instruction
mov edi, eax              ; original instruction
jmp @YourNewReturnLabel   ; return the original code
```

**Comment by MishaIac** [comment]
> ```assembly
> pushad                    ; backup the registers
> call @GetProc             ; get the SRL pointer
> push dword [ebp+0x4]      ; get the string pointer and put in the stack
> call eax                  ; execute the SRL
> add esp, 4                ; Discard the string pointer given to the SRL
> popad                     ; restore the  original registers values
> mov ebx, dword [ebp+0x4]  ; original instruction
> mov edi, eax              ; original instruction
> jmp YourNewReturnLabel    ; return the original code
> ```

I tried this code, and the game does not crash now, but now the text is not parsed, and after initialization, only one line appeared: 
![image](https://user-images.githubusercontent.com/47920105/128766757-4db07198-764a-48bf-adef-9bf1b3d86cf1.png)
Maybe it's still the wrong instruction?

**Comment by marcussacana** [comment]
Wrong Encoding Probabbly...
You can change the encoding in the SRL.ini

**Comment by marcussacana** [comment]
Also I fixed a bug in that assembly code, update it

**Comment by MishaIac** [comment]
Having corrected the code, and also changed 0x4 to 0xC (the text was like this because of this, and not the encoding), the text is parsed (but not all lines) while inserting the translation into .lst - nothing changes (that is, the translation is not inserted into game)

It seems to me that in the end this is the wrong instruction :(

**Comment by marcussacana** [comment]
Show me your final code and how is the SRL log output
you can make the SRL show the log changing in the SRL.ini the LogLevel=TRC and LogFile=true, maybe Log=true too

**Comment by MishaIac** [comment]
> Show me your final code and how is the SRL log output
> you can make the SRL show the log changing in the SRL.ini the LogLevel=TRC and LogFile=true, maybe Log=true too

[SRL.log](https://github.com/marcussacana/StringReloads/files/6957341/SRL.log)
![image](https://user-images.githubusercontent.com/47920105/128772701-98660500-5350-4ceb-a50b-3bef3a06ac2f.png)

**Comment by marcussacana** [comment]
Okay, First, you're using a very old version of the SRL, I recommend update it.
Second, while debugging you verified if the SRL returned the correct translation in the EAX?
Third, the original code is in the VM60.dll and you put the patch in the game exe, this is very wrong and probabbly your patch will works only in your machine if you don't move the patched code to the .dll as well.

Anyway, looks like isn't possible inject the string in this part, you should seek with help of the stack what fuction called this function with the string to find from the that `[ebp+0xC]` came, trying inject the SRL in a more early in the code.

**Comment by MishaIac** [comment]
I will try to do something else, and if it also does not work, then the translation will have to be postponed indefinitely. Anyway, thanks for trying to help.

**Comment by MishaIac** [comment]
Solved.
